language: python
sudo: required
dist: xenial
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - py.test src --cov=src --cov-report term-missing

notifications:
  email: false

after_success:
  - coveralls
